config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks


  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    @bookmark.save
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to list_path(bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
  end

  def create
    @list = List.new(list_params)
    @list.save
    if @list.save
      redirect_to lists_path
    else
      @lists = List.all
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>Add a new bookmark 📔</h1>
<hr>


<div>
  <%= simple_form_for [@list, @bookmark] do |f|%>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>
<hr>

<p><%= link_to "Back", list_path(@list), class: "btn btn-primary" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner" id="home_banner">
  <h1 class="container">What kind of film do you want ?</h1>
</div>

<div class="container" id="index_container">
  <div class="cards">
      <% @lists.each do |list| %>
          <%= link_to list_path(list), class:"card-link" do %>
          <div class="card-category <%= list.name %>"><p><%=list.name%></p> </div>
          <% end %>
      <% end %>
  </div>
<hr>
  <h3>Add a new list ?</h3>
    <div>
      <%= render "form", list:@list %>
    </div>
</div>
<%=  %>

app/views/lists/show.html.erb
<div class="banner" id="show_banner">
  <h1 class="container"><%= @list.name.capitalize %></h1>
</div>

<%= link_to "Back", lists_path, class: "btn btn-primary" %>
<hr>

<ul>
  <% @list.movies.each do |movie| %>
    <p><%= movie.title%> - rating : <%= movie.rating.to_f%>/10 - <%= link_to "delete", bookmark_path(movie.bookmarks.where(list_id: @list.id).first.id) ,data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger"%></p>
    <img alt="<%= movie.title%>" width="200" src="<%= movie.poster_url%>">
    <p><%= movie.overview%></p>
  <% end %>
</ul>

<hr>
<p><%= link_to  "Add a new movie to your list", new_list_bookmark_path(@list), class: "btn btn-primary"%></p>